gt:
  axis:
    wxmpUrl: http://hz1.yifriend.net/
    wxmpSignKey: WXMP2017
    memberSignKey: MV8MMFQUMU1HJ6F2GNH40ZFJJ7Q8LNVM
    memberUrl: https://member.deeptel.com.cn/
    signKey: goodtom2016@shortUrl.
    serviceUrl: http://short.duofee.com/
server:
  port: 9090